### ISSUE TITLE
Displaying free pixel count (or dimensions of available space) in AtlasViewer view

### ISSUE THREAD

**Issue by Chaos02** [XFactHD/AtlasViewer#4]
Hi - just thought about two minor enhancements:
- Displaying available unused texture space on the atlas as dimensions and maximum texture atlas size
- Counting how much space a certain (mod) domain takes up on the atlas

I'd guess this is a pretty simple feature but I think for sure they would be a welcome one to ressourcepack creators (especially for modpacks)
It lets you approximate, how much texture patches still fit on the atlas and at which resolution they should fit

greetings ^^

**Comment by XFactHD** [comment]
Adding more info about the atlas itself is planned, I just have to be careful to not make the information confusing or even outright misleading. This is especially relevant for the atlas size because it is variable and can grow up to the maximum texture size supported by the GPU (on modern hardware this is between 8k x 8k and 32k x 32k depending on the GPU model).
Showing how much of the used space and total space each namespace consumes is definitely a useful addition I will include.

**Comment by Chaos02** [comment]
Hey - just a question - could you create a minor release for 1.18 including this? Would be really great!!

https://github.com/XFactHD/AtlasViewer/commit/a41cbb8fd759be9dec75335ea4651c536d7cb9ef

**Comment by XFactHD** [comment]
I don't know yet. Parts of the texture atlas system have received significant changes between 1.18 and 1.20, meaning it's significantly more work than just copying the code to the older versions and quickly making sure it works. I'll look into the feasibility of a backport but I won't promise anything.

**Comment by XFactHD** [comment]
I have decided to not do any backports for now. I currently simply don't have the time needed to dig into the significant changes to the texture atlas system again and backport this.

**Comment by Chaos02** [comment]
*sadge* thanks anyways! great work, you really helped me troubleshoot my ressource pack issues, being basically the only one aside Continuum Textures that has any information about maximum texture atlas size ^^
